<h1 class="mt-5 mb-3 text-xl text-gray-700 text-center">CLIENT AGREEMENT</h1>
<div class="text-gray-500">
	<p class="mb-3">This Agreement determines the terms and conditions of use by the Visitors of the materials on the website www.alpha-trade.in (hereinafter referred to as the "Site").</p>
	<p class="mb-3">1. General conditions</p>
	<p class="mb-3"> 1.1. Any use of the materials and services of the Site is not regulated.<br>
	1.2. This Agreement is a public offer. By accessing the materials of the Site, the User is deemed to have acceded to this Agreement.<br>
	1.3. The Administration of the Site has the right at any time to unilaterally change the terms of this Agreement. Such changes come into force from the moment the new version of the Agreement is posted on the site. If the User disagrees with the changes made, he must refuse access to the Site, stop using the materials and services of the Site.<br>
	</p>
	<p class="mb-3">2. Obligations of the User</p>
	<p class="mb-3">
	2.1. The User agrees not to take any actions that lead or may lead to a disruption to the normal operation of the Site and the services of the Site.<br>
	2.2. Use of the Site materials in the media is not allowed.<br>
	2.3. Any citation and publication of the Site materials, including the publication of a link to the Site on third-party resources is prohibited.<br>
	2.4. Comments and other entries of the User on the Site are prohibited.<br>
	2.5. The user is warned that the Site Administration is not responsible for visiting and using the Site and materials published on the site, including external resources, links to which may be contained on the site.<br>
	2.6. The User agrees that the Administration of the Site is not liable and does not have any direct or indirect obligations to the User in connection with any possible or occurred losses or losses connected with any content of the Site, registration of copyright and information about such registration, goods or services, accessible to or received through external sites or resources or other contacts of the User, to which he entered, using information posted on the Site or links to external resources.<br>
	2.7. The user accepts the provision that all materials and services of the Site or any part thereof may be accompanied by advertising. The User agrees that the Site Administration does not bear any responsibility and does not have any obligations in connection with such advertising.<br>
	</p>
	<p class="mb-3">3. Other conditions</p>
	<p class="mb-3">
	3.1. All possible disputes arising from or related to this Agreement shall be resolved in accordance with the current Agreement.<br>
	3.2. Nothing in the Agreement can be understood as the establishment of agency relations between the User and the Site Administration, partnership relations, joint activities, personal rental relationships, or any other relations not expressly provided for in the Agreement.<br>
	3.3. Recognition by the Administration of the Site of any provision of the Agreement as invalid or unenforceable does not entail invalidity of other provisions of the Agreement.<br>
	3.4. Inaction on the part of the Site Administration in case of violation of the provisions of the Agreement by any of the Users does not deprive the Site Administration of the right to take later appropriate actions in defense of its interests and protection of the Site materials.<br>
	</p>
	<p class="mb-3">4. Disclaimer of Liability</p>
	<p class="mb-3">1. The information placed on the pages of the Site is intended for free familiarization of users with questions that may be of interest to them.<br>
	2. All information is provided in its original form, without guarantees of completeness or timeliness, and without other express or implied warranties. Access to the Site, as well as the use of its Content, is carried out exclusively at your discretion and at your own risk.<br>
	3. Administration (Site owners, officials, directors, shareholders, founders, editors, employees, agents, administrators, moderators, moderators, moderator assistants, routers, curators and others) does not exclude the possibility of errors in the information provided on the Site and is not responsible for the accuracy and reliability of the information.<br>
	4. The Site and its Content are provided freely, as an act of goodwill, on an "as is" basis, without entering into any agreements or agreements between you, users of this Site, the Administration, the owners of the servers on which it is hosted, or by someone still, in any way connected with this or related projects, which [contracts] can become the subject of direct claims.<br>
	5. The Administration does not give any assurances or guarantees regarding the Site and its Content, including without limitation, timeliness, relevance, accuracy, completeness, reliability, accessibility or compliance for any particular purpose of the Site and the Content, with respect to the fact that when using the Site, there will be no errors, it will be safe and uninterrupted, that the Administration will correct any errors, or that the Site will not contain viruses or other malicious codes, and that the Content and the Site do not violate rights of third parties.<br>
	6. Some links on this Site lead to resources located on third-party sites. These links are placed for the convenience of users and do not mean that the Administration approves the content of other sites. In addition, the Site Administration assumes no responsibility for the availability of these resources and for their content. This statement applies to all links provided on the Site and to the materials of all websites accessible through banners and links on the website at<br>
	7. It is the responsibility of the Administration not to control the legality or illegality of the information transmitted (any, including but not limited to information transmitted between users, internal transfer of information in the form of various links, texts or archives), determining the ownership or legitimacy of the transfer, reception or use this information.<br>
	8. The Administration takes reasonable steps to ensure the accuracy, relevance and legitimacy of the Content, but it does not assume responsibility for the actions of persons or organizations, directly or otherwise carried out on the basis of information available on the Site or received through it, as provided by the Administration, so and third parties.<br>
	9. The Administration disclaims any representations or warranties that may otherwise be implied and disclaims liability in respect of the Site, the Content and its use. Under no circumstances will the Site Administration be liable to any party for any direct, indirect, special or other indirect damage as a result of any use of information on this Site or on any other website to which there is a hyperlink from our Site, the occurrence of dependence, decrease in productivity, dismissal or interruption of labor activity, as well as deductions from educational institutions, for any lost profits, suspension of economic activities, loss of programs or data in Your information systems or otherwise, arising from the access, use or inability to use the Site, the Content or any linked Internet site, or the inability, error, omission, interruption, defect, idle time or delay in transmission, computer virus or a system failure, even if the administration is explicitly informed of the possibility of such damage.<br>
	10. For advertising placed on the Site, only the advertiser is liable. The site specifically notifies that it does not guarantee the possibility of purchasing or using certain goods or services at prices and / or on terms specified in the advertising blocks (texts, banners). You agree that the Site is not responsible for any consequences (including any damage) arising from any relationship with advertisers.<br>
	11. The Site provides an opportunity for users to publish comments on published materials. Administration of the site does not bear any responsibility for the content of comments and the accuracy of the information published in them, also, the Site is not responsible for any recommendations or opinions that may be contained in the comments. In addition, because the Internet does not provide a fully reliable protection of information, the Site is not responsible for the information sent via the Internet.<br>
	12. By submitting materials to the Site, the sending party guarantees and confirms that it has copyright to these materials, has received permission to publish from the copyright holder, or that these materials are in the public domain and are placed in accordance with the requirements of the original source. The sending party also guarantees and confirms that the recipient has a full and unlimited right to send these materials, and that such sending does not infringe on anyone's rights and legitimate interests. The Administration of the Site is not responsible for the materials sent to the site.<br>
	13. The site may use cookies to store both your personal and general information. "Cookies" are small text files that can be used by the website to identify repeat visitors, to simplify the access and use of the site visitor, as well as to track visitors to the site and collect general information to improve the content. By using the Site, you agree to use the Site to use cookies.<br>
	14. Administration reserves the right to make changes without notification of users. Also, the Administration is not responsible for changing, editing or deleting any information that you added to the Site or other related projects.<br>
	15. The Administration has the right to deny access to the Site to any User or group of Users without explaining the reasons for their actions and prior notification.<br>
	16. Administration has the right to change or delete links to information, graphic, sound and other data posted by Users on the Site, without prior notification and explanation of the reasons for their actions. 17. Any trademarks, signs and names of goods, services and organizations, design rights, copyrights and related rights that are mentioned, used or quoted on the pages of the Site, belong to their rightful owners and their use here does not entitle you to any other use . Unless otherwise stated, the pages of this Site are in no way connected with the rightholders, and no one except the rightholder can dispose of the rights to use copyrighted materials. You are responsible for using these and similar materials.<br>
	17. Reading, distribution or modification of information posted on this site may violate the laws of the country in which you are viewing this site.<br>
	18. The User agrees that all possible disputes will be resolved according to the norms of this Agreement. 20. The user agrees that consumer protection laws and laws can not be applied to the use of the Site by him, since he does not provide reimbursable services.<br>
	19. Inaction on the part of the Administration in case of violation of the user agreement by the User or group of Users does not deprive the Administration of the right to take appropriate actions in defense of the interests of the Site later.<br>
	20. If, in accordance with the current Agreement, any conditions are declared invalid, the remaining conditions remain in full force.<br></p>
	{{-- Link to rus version --}}
	<p class="mb-3">By using this Site, you agree to the "Waiver of Liability" and the established Rules and accept all responsibility that may be assigned to you. It is a translation. There may be errors or the page may be out of date with respect to the 
		<button 
			type="button"
			class="text-blue-400 underline font-medium"
			x-on:click="showTosEn = false; showTosRu = true"
		>
			original version
		</button>.
	</p>
</div>